[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
"@layerzerolabs-oft-evm" = "3.1.4"
"@layerzerolabs-oapp-evm" = "0.3.2"
"@layerzerolabs-lz-evm-protocol-v2" = "3.0.100"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
